require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegCardsController do

  # This should return the minimal set of attributes required to create a valid
  # RegCard. As you add validations to RegCard, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegCardsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reg_cards as @reg_cards" do
      reg_card = RegCard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reg_cards).should eq([reg_card])
    end
  end

  describe "GET show" do
    it "assigns the requested reg_card as @reg_card" do
      reg_card = RegCard.create! valid_attributes
      get :show, {:id => reg_card.to_param}, valid_session
      assigns(:reg_card).should eq(reg_card)
    end
  end

  describe "GET new" do
    it "assigns a new reg_card as @reg_card" do
      get :new, {}, valid_session
      assigns(:reg_card).should be_a_new(RegCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested reg_card as @reg_card" do
      reg_card = RegCard.create! valid_attributes
      get :edit, {:id => reg_card.to_param}, valid_session
      assigns(:reg_card).should eq(reg_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RegCard" do
        expect {
          post :create, {:reg_card => valid_attributes}, valid_session
        }.to change(RegCard, :count).by(1)
      end

      it "assigns a newly created reg_card as @reg_card" do
        post :create, {:reg_card => valid_attributes}, valid_session
        assigns(:reg_card).should be_a(RegCard)
        assigns(:reg_card).should be_persisted
      end

      it "redirects to the created reg_card" do
        post :create, {:reg_card => valid_attributes}, valid_session
        response.should redirect_to(RegCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reg_card as @reg_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        RegCard.any_instance.stub(:save).and_return(false)
        post :create, {:reg_card => {}}, valid_session
        assigns(:reg_card).should be_a_new(RegCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RegCard.any_instance.stub(:save).and_return(false)
        post :create, {:reg_card => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reg_card" do
        reg_card = RegCard.create! valid_attributes
        # Assuming there are no other reg_cards in the database, this
        # specifies that the RegCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RegCard.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => reg_card.to_param, :reg_card => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested reg_card as @reg_card" do
        reg_card = RegCard.create! valid_attributes
        put :update, {:id => reg_card.to_param, :reg_card => valid_attributes}, valid_session
        assigns(:reg_card).should eq(reg_card)
      end

      it "redirects to the reg_card" do
        reg_card = RegCard.create! valid_attributes
        put :update, {:id => reg_card.to_param, :reg_card => valid_attributes}, valid_session
        response.should redirect_to(reg_card)
      end
    end

    describe "with invalid params" do
      it "assigns the reg_card as @reg_card" do
        reg_card = RegCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RegCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => reg_card.to_param, :reg_card => {}}, valid_session
        assigns(:reg_card).should eq(reg_card)
      end

      it "re-renders the 'edit' template" do
        reg_card = RegCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RegCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => reg_card.to_param, :reg_card => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reg_card" do
      reg_card = RegCard.create! valid_attributes
      expect {
        delete :destroy, {:id => reg_card.to_param}, valid_session
      }.to change(RegCard, :count).by(-1)
    end

    it "redirects to the reg_cards list" do
      reg_card = RegCard.create! valid_attributes
      delete :destroy, {:id => reg_card.to_param}, valid_session
      response.should redirect_to(reg_cards_url)
    end
  end

end
